### ISSUE TITLE
Proposal: Xarray user stories

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xarray.dev#272]
Xarray is used in a wide range of scientific and applied research domains but many have the impression that Xarray is just for geospatial data. One way we could counter this misconception is by developing a series of user stories that highlights the complete range of Xarray applications. I'm thinking of a list of at least 10 stories that could be highlighted on this website (either as stand-alone pages or a special blog post category).

Domains:

- [x] Neuroscience (e.g. Allen Brain Atlas / SDK) (see #345)
- [ ] Bioimaging (see #344)
- [ ] Genomics (see #346)
- [ ] Climate model analysis  (see #349)
- [ ] Remote sensing analysis (see #350)
- [x] Machine learning and/or statistics (e.g. pymc, arviz) (see #348)
- [ ] Finance
- [ ] Economics (see #347)
- [ ] Physics (see #352)
- [ ] Energy sector analytics (see #358)
- [ ] [more here]

If folks think this is a good idea and we can settle on a basic format for the stories, I'll volunteer to solicit and edit the stories.

cc xarray-devs (@alexamici, @rabernat, @shoyer, @dcherian, @benbovy, @max-sixty, @spencerkclark, @fujiisoup, @fmaussion, @mathause, @andersy005, @Illviljan, @keewis, @TomNicholas)

ps, I'll create the xarray-core-team in this org so we don't have to tag individuals in the future

**Comment by fmaussion** [comment]
Good idea - I think they should be short and illustrate one specific use case in each of the disciplines listed here. I can think of contributing an example with a nD cube of model output / parameters resulting of an international model intercomparison experiment, but this may take some time.

**Comment by dcherian** [comment]
I agree fully! 

On a related note, I started adding links to domain-specific tutorials on the tutorial website: https://github.com/xarray-contrib/xarray-tutorial/pull/133 . When you contact people to write these, it'd be nice to ask them for similar tutorial/workshop resources in their field we could link to.
